name: Mirror

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Mirror Repository
      uses: spyoungtech/mirror-action@v0.1.1
      with:
        args: https://projects.cs.nott.ac.uk/psyao5/UoN-CompSci-discord-bot.git
      env:
        GIT_USERNAME: psyao5
        GIT_PASSWORD: $${secrets.GIT_PASSWORD}}
